# Generated by Django 4.1.2 on 2022-10-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coorientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('universidade', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('lattes', models.URLField()),
                ('google_scholar', models.URLField()),
                ('research_gate', models.URLField()),
                ('linkedin', models.URLField()),
                ('orcid', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
    ]
